#pragma once

#include "config.hpp"
#include "video_capture.hpp"

#include <nlohmann/json.hpp>

#include <protocol/json_rpc_adapter.hpp>

#include <ymir/debug/protocol/debug_types.hpp>
#include <ymir/sys/saturn.hpp>

#include <atomic>
#include <condition_variable>
#include <cstdint>
#include <memory>
#include <mutex>
#include <optional>
#include <string>
#include <string_view>
#include <thread>
#include <vector>

namespace ymir::debug {

/// Owns one Saturn instance and serializes debugger access against continuous
/// execution. The protocol thread accesses the core only while it is paused;
/// the execution thread is the sole owner while frames are running.
class DebugService {
public:
    explicit DebugService(HeadlessConfig config);
    ~DebugService();

    DebugService(const DebugService &) = delete;
    DebugService(DebugService &&) = delete;
    DebugService &operator=(const DebugService &) = delete;
    DebugService &operator=(DebugService &&) = delete;

    /// Loads the configured IPL, optional disc and optional backup RAM, then
    /// hard-resets the Saturn into a paused state.
    [[nodiscard]] bool Initialize(std::string &outError);

    /// Builds the first protocol message emitted by ymir-headless.
    [[nodiscard]] nlohmann::json CreateReadyNotification() const;

    /// Parses and dispatches one JSON-RPC line. Valid notifications intentionally
    /// return no response, as required by JSON-RPC 2.0.
    [[nodiscard]] std::optional<nlohmann::json> HandleLine(std::string_view line);

    /// Removes notifications generated by the preceding request. The caller
    /// writes the request response first, then these notifications, preserving
    /// deterministic response/event ordering for pause and bounded execution.
    [[nodiscard]] std::vector<nlohmann::json> TakePendingNotifications();

    [[nodiscard]] ExecutionState GetState() const noexcept {
        return m_state.load(std::memory_order_acquire);
    }

    [[nodiscard]] bool ShutdownRequested() const noexcept {
        return m_shutdownRequested.load(std::memory_order_acquire);
    }

private:
    [[nodiscard]] nlohmann::json DispatchRequest(const JsonRpcRequest &request);
    [[nodiscard]] nlohmann::json CreateDebugError(const JsonRpcRequest &request, JsonRpcError rpcError,
                                                  ErrorCode debugError, std::string_view message) const;
    [[nodiscard]] bool IsTargetEnabled(DebugTarget target) const noexcept;
    void StartExecutionThread();
    void StopExecutionThread();
    void ExecutionThreadMain();
    void ApplyPendingInputFrame();
    void ClearPendingInput();
    void QueueStoppedNotificationLocked(StopReason reason);
    void CaptureVideoFrame(const uint32_t *framebuffer, uint32_t width, uint32_t height);
    void ClearVideoFrame();
    [[nodiscard]] std::optional<CapturedVideoFrame> SnapshotVideoFrame();

    HeadlessConfig m_config;
    std::unique_ptr<ymir::Saturn> m_saturn;
    std::atomic<ExecutionState> m_state{ExecutionState::Starting};
    std::atomic_bool m_shutdownRequested{};
    std::atomic_bool m_slaveTargetEnabled{};
    std::string m_instanceId{"local-001"};

    std::mutex m_executionMutex;
    std::condition_variable m_executionCondition;
    std::condition_variable m_pausedCondition;
    std::thread m_executionThread;
    bool m_workerStopRequested{};
    bool m_continueRequested{};
    bool m_pauseRequested{};
    uint16_t m_inputButtons{0xFFF8U};
    uint32_t m_inputFramesRemaining{};
    bool m_inputReleasePending{};
    uint32_t m_stopSequence{};
    std::vector<nlohmann::json> m_pendingNotifications;

    std::mutex m_videoMutex;
    std::vector<uint32_t> m_videoPixels;
    uint32_t m_videoWidth{};
    uint32_t m_videoHeight{};
    uint64_t m_videoFrameSequence{};
    bool m_hasVideoFrame{};
};

} // namespace ymir::debug
